[package]
name = "dynsync"
version = "0.1.0"
authors = ["Jianing Yang <jianingy.yang@gmail.com>"]

[dependencies]
inotify = "*"
docopt = "0.6"
rustc-serialize = "0.3"
regex = "0.1"
log = "0.3"
env_logger = "0.3"
time = "0.1"
